name: Deploy Backend to ECR

# El pipeline se activa automáticamente al hacer un push en la rama main
# siempre y cuando cambien archivos dentro de la carpeta 'backend'
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 304744337786.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: innovatech-backend
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build and Push Backend Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        # Entrar a la carpeta del backend donde está el Dockerfile
        cd backend
        
        # Construir la imagen Docker usando las variables de entorno configuradas arriba
        docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
        
        # Subir la imagen al repositorio privado en AWS ECR
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}